@BASE_URL = http://127.0.0.1:8000

####
POST {{ BASE_URL }}/api/auth/register
Content-Type: application/json

{
  "email": "asj214@naver.com",
  "name": "sjahn",
  "password": "rewq1234"
}

####
# @name authentication
POST {{ BASE_URL }}/api/auth/login
Content-Type: application/json

{
  "email": "asj214@naver.com",
  "password": "rewq1234"
}

###
@token = {{ authentication.response.body.token }}


###
GET {{ BASE_URL }}/api/auth/me
Content-Type: application/json
Authorization: Bearer {{ token }}


###
GET {{ BASE_URL }}/api/memos
Content-Type: application/json
Authorization: Bearer {{ token }}


###
POST {{ BASE_URL }}/api/memos
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "body": "Another User Modify Test Memo"
}

###
GET {{ BASE_URL }}/api/memos/1
Content-Type: application/json
Authorization: Bearer {{ token }}


###
PUT {{ BASE_URL }}/api/memos/5
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "body": "You Are Bad Man"
}

###
DELETE {{ BASE_URL }}/api/memos/2
Content-Type: application/json
Authorization: Bearer {{ token }}

###
GET {{ BASE_URL }}/api/hiragana
Content-Type: application/json
Authorization: Bearer {{ token }}


###
GET {{ BASE_URL }}/api/hiragana/practice
Content-Type: application/json
Authorization: Bearer {{ token }}
