# Generated by Django 4.2.11 on 2024-05-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiragana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('word', models.CharField(max_length=30, unique=True, verbose_name='단어')),
                ('pronunciation', models.CharField(max_length=30, verbose_name='단어')),
            ],
            options={
                'db_table': 'hiragana',
                'ordering': ['-id'],
            },
        ),
    ]
